const FieldTypes = {
  NONE: 'FIELD_TYPES/NONE',
  SELECTED: 'FIELD_TYPES/SELECTED',
  AVAILABLE: 'FIELD_TYPES/AVAILABLE',
  FROG: 'FIELD_TYPES/FROG',
  NEXT_JUMP: 'FIELD_TYPES/NEXT_JUMP',
};

export default FieldTypes;
